### PR TITLE
Increase list of acceptable channel of delivery codes from 8 to 32

### PR DESCRIPTION
**Pull request by edavey**
See [Zendesk support ticket 15791](https://dxw.zendesk.com/agent/tickets/15791)

This ticket asks for the number of "accepted" channel of delivery codes to be increased from 8 to 32. 

## Background

The FCDO (Foreign, Commonwealth & Development Office) have asked for more detailed information on who is spending the aid donated. i.e. what type of entity are the "implementing organisations".

### Current code usage

```
| channel_of_delivery_code | activity_count |
| ------------------------ | -------------- |
| 11000                    | 2,663          |
| 11001                    | 31             |
| 20000                    | 1,265          |
| 22000                    | 83             |
| 40000                    | 1              |
| 51000                    | 3,308          |

```

### The Future

Ultimately the "channel of delivery" step is expected to
become redundant as each "implementing organisation" should
have an assigned channel of delivery code. Once it's
mandatory to associate at least one implementing organisation
with an activity, this step can be removed and an activity's
channel of delivery code(s) can be derived through its
implementing organisations.

## New codes requested

- 11002: Local Government
- 11003: Public corporations
- 12000: Recipient Government
- 12001: Central Government
- 12002: Local Government
- 12003: Public corporations
- 12004: Other public entities in recipient country
- 13000: Third Country Government (Delegated co-operation)
- 21000: International NGO
- 23000: Developing country-based NGO
- 30000: Public-Private Partnerships (PPP) and Networks
- 31000: Public-Private Partnerships (PPP)
- 32000: Networks
- 41000: United Nations (UN) agency, fund or commission
- 42000: European Union Institutions
- 43000: International Monetary Fund (IMF)
- 44000: World Bank Group (WB)
- 45000: World Trade Organisation (WTO)
- 46000: Regional Development Banks
- 47000: Other multilateral institutions
- 60000: Private Sector Institutions
- 61000: Private sector in provider country
- 62000: Private sector in recipient country
- 63000: Private sector in third country

## Distinguishing Donor and Recipient sub-codes

We now display the implicit Donor/Recipient hierarchies in the select list labels, by
editing the names of the codes in the "codelist" configuration file:

11000: Donor Government
11001: Donor Government > Central Government
11002: Donor Government > Local Government
11003: Donor Government > Public corporations
11004: Donor Government > Other public entities in donor country
12000: Recipient Government
12001: Recipient Government > Central Government
12002: Recipient Government > Local Government
12003: Recipient Government > Public corporations
12004: Recipient Government > Other public entities in recipient country

The list of acceptable codes is now:

```
| code  | name                                                  | category       | 
| ----- | ----------------------------------------------------- | -------------- |
| 11000 | Donor Government                                      | Donor Govt     |
| 11001 | Central Government                                    | Donor Govt     |
| 11002 | Local Government                                      | Donor Govt     |
| 11003 | Public corporations                                   | Donor Govt     |
| 11004 | Other public entities in donor country                | Donor Govt     |
| 12000 | Recipient Government                                  | Recipient Govt |
| 12001 | Central Government                                    | Recipient Govt |
| 12002 | Local Government                                      | Recipient Govt |
| 12003 | Public corporations                                   | Recipient Govt |
| 12004 | Other public entities in recipient country            | Recipient Govt |
| 13000 | Third Country Government (Delegated co-operation)     |                |
| 20000 | Non-Governmental Organisation (NGO) and Civil Society |                |
| 21000 | International NGO                                     |                |
| 22000 | Donor country-based NGO                               |                |
| 23000 | Developing country-based NGO                          |                |
| 30000 | Public-Private Partnerships (PPP) and Networks        |                |
| 31000 | Public-Private Partnerships (PPP)                     |                |
| 32000 | Networks                                              |                |
| 40000 | Multilateral Organisations                            |                |
| 41000 | United Nations (UN) agency, fund or commission        |                |
| 42000 | European Union Institutions                           |                |
| 43000 | International Monetary Fund (IMF)                     |                |
| 44000 | World Bank Group (WB)                                 |                |
| 45000 | World Trade Organisation (WTO)                        |                |
| 46000 | Regional Development Banks                            |                |
| 47000 | Other multilateral institutions                       |                |
| 51000 | University, college or other teaching institution...  |                |
| 60000 | Private Sector Institutions                           |                |
| 61000 | Private sector in provider country                    |                |
| 62000 | Private sector in recipient country                   |                |
| 63000 | Private sector in third country                       |                |
| 90000 | Other                                                 |                |
```

- [ ] Is an ADR required? An ADR should be added if this PR introduces a change to the architecture.
- [ ] Is a changelog entry required? An entry should always be made in `CHANGELOG.md`, unless this PR is a small tweak which has no impact outside the development team.
- [ ] Do any environment variables need amending or adding?
- [ ] Have any changes to the XML been checked with the IATI validator? See [XML Validation](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/doc/xml-validation.md)

### CODE REVIEW

**Comment by edavey** [comment]
One other question to be resolved is whether any of the newly acceptable channel of delivery codes need to be included in the mapping between collaboration types and delivery codes. See https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/master/vendor/data/codelists/BEIS/accepted_collaboration_types_and_channel_of_delivery_mapping.yml

We *think* that it isn't necessary, but we need to check with FCDO users.

**Comment by edavey** [comment]
see also this information from IATI https://iatistandard.org/en/iati-standard/201/codelists/crschannelcode/ (thanks @dragon-dxw )

**Comment by edavey** [comment]
Regarding the question of:

> whether any of the newly acceptable channel of delivery codes need to be included in the mapping between collaboration types and delivery codes

See https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/master/vendor/data/codelists/BEIS/accepted_collaboration_types_and_channel_of_delivery_mapping.yml

I'm wondering if the "code 3: Bilateral, core contributions to NGOs and other private bodies / PPPs" mapping now needs to be extended to include these 4 newly acceptable code:

- 21000: International NGO
- 23000: Developing country-based NGO
- 30000: Public-Private Partnerships (PPP) and Networks
- 31000: Public-Private Partnerships (PPP)

Can we get Josh to take a look?

**Comment by edavey** [comment]
Josh has confirmed that no changes need to be made to the mapping of channel of delivery codes to collaboration types.

**Review by dragon-dxw — APPROVED** [review]

**Pull request merged**
