### PR TITLE
Update Organisation format error message

### PR DESCRIPTION
**Pull request by pezholio**
The existing error message was misleading

### CODE REVIEW

**Comment by CristinaRO** [comment]
[Add new delivery partner short name error is incorrect](https://trello.com/c/EXg9ZkoJ/1960-add-new-delivery-partner-short-name-error-is-incorrect)

**Review by CristinaRO — COMMENTED** [review]
Would it be worth having a unit spec for this specific kind of validation? The current spec only checks that we have presence validation.

**Comment by pezholio** [comment]
Good plan! Done 👍

**Review by CristinaRO — APPROVED** [review]
Thank you! 👍🏻

**Pull request merged**
