### PR TITLE
Changed "activate user" to "What is the user's status?

### PR DESCRIPTION
**Pull request by duffylouise**
## Changes in this PR

Changed "Activate user" to "What is the user's status?" to be more consistent with other titles 

## Next steps

- [ ] Is an ADR required? An ADR should be added if this PR introduces a change to the architecture.
- [ ] Is a changelog entry required? An entry should always be made in `CHANGELOG.md`, unless this PR is a small tweak which has no impact outside the development team.
- [ ] Do any environment variables need amending or adding?
- [ ] Have any changes to the XML been checked with the IATI validator? See [XML Validation](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/doc/xml-validation.md)

### CODE REVIEW

**Comment by duffylouise** [comment]
[Improve "create user" content](https://trello.com/c/xvC7QcWI/677-improve-create-user-content)

**Comment by lozette** [comment]
@duffylouise I think the actual interface has changed since this ticket was created, it currently looks like this:

Screenshot 2020-06-22 at 11 46 14

Is the wording you meant to change "Active?"

**Comment by duffylouise** [comment]
Yeah, so this is another one where the recommendation is for the title and hint text to merge so it should be:

Title: What is the user's status?
Hint text: Deactivated users cannot login

**Comment by lozette** [comment]
@duffylouise OK in that case the string you need to change is on line 22 of that file, and the hint that needs removing is on line 27

**Comment by duffylouise** [comment]
Should I do a new pull request for these changes? I can do them this afternoon

**Comment by lozette** [comment]
You can add them to this PR, or start a new one - whichever is easiest for you!

**Comment by duffylouise** [comment]
I'll start a new one to make it easier for myself. My brain's like mashed potato today.

**Pull request closed without merging**
