### PR TITLE
Update to ruby 3.0

### PR DESCRIPTION
**Pull request by jkempster34**
## Trello
https://trello.com/c/7Bq3osUp

### DRY up references to Ruby version
Currently, we declare the ruby version in `.ruby-version` as well as in the
`Gemfile`.

DRY them up so that we don't forget one when updating.

### Fix deprecated keyword argument behaviour
Ruby 2.7 deprecated certain behaviours of keyword arguments; these will be a
breaking change in Ruby 3.0. 

Before updating to Ruby 3.0, fix the deprecation warnings.

Some forms were using `include_blank` incorrectly, which meant that the select
component of the formbuilder wasn't generating the desired blank element. Now
that this is fixed, we can remove the structs that were replicating this
behaviour in the FormHelper.

### Remove unused method
This method isn't called anywhere and can be safely removed.

### Update Ruby to 3.0.5
Update Ruby to the latest patch version of 3.0.

### Remove EOL Ruby warning from Brakeman ignore
We have been ignoring a Brakeman warning that support for Ruby 2.7 is ending
shortly. This is no longer needed now that we are using Ruby 3.0

### Fix Ruby 3.0 Standard errors
In Ruby 3.0 `Regexp` is automatically frozen, so the call to `freeze` is now
redundant.

### Match bundler version in Dockerfile
When building the Dockerfile we see `Bundler 2.3.5 is running, but your
lockfile was generated with 2.3.9. Installing Bundler 2.3.9 and restarting
using that version.`

Match the bundler version in the Dockerfile to the version in the lockfile.

### CODE REVIEW

**Review by yndajas — COMMENTED** [review]
This looks good and the server seems to load fine on my machine. I'll check the UI and bulk upload journeys for adding activities tomorrow, but things seem to load properly when clicking around

One thing I spotted is these errors in the server logs when opening `/reports`

```
17:46:23 web.1    | IOError (closed stream):
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_dispatch/http/response.rb:127:in `write'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/live.rb:157:in `write'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/live.rb:265:in `rescue in block (2 levels) in process'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/live.rb:262:in `block (2 levels) in process'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies/interlock.rb:42:in `block in running'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/concurrency/share_lock.rb:162:in `sharing'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies/interlock.rb:41:in `running'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/live.rb:253:in `block in process'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/live.rb:303:in `block in new_controller_thread'
17:46:23 web.1    |
17:46:23 web.1    |
17:46:23 web.1    |
17:46:23 web.1    | Pundit::PolicyScopingNotPerformedError (ReportsController):
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/pundit-2.3.0/lib/pundit/authorization.rb:49:in `verify_policy_scoped'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:427:in `block in make_lambda'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:516:in `block in invoke_after'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:516:in `each'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:516:in `invoke_after'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:107:in `run_callbacks'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/notifications.rb:203:in `block in instrument'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/notifications.rb:203:in `instrument'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/abstract_controller/base.rb:165:in `process'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionview-6.1.7.1/lib/action_view/rendering.rb:39:in `process'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/live.rb:261:in `block (2 levels) in process'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies/interlock.rb:42:in `block in running'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/concurrency/share_lock.rb:162:in `sharing'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies/interlock.rb:41:in `running'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/live.rb:253:in `block in process'
17:46:23 web.1    |   /Users/yndajas/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/live.rb:303:in `block in new_controller_thread'
```

**Comment by yndajas** [comment]
It looks like that error may be unrelated to this upgrade - I'm getting it on `develop` too, and so is George. Would probablu be good to confirm Cristina and George are able to run this fine in their local environments, but otherwise I think it's good to go

**Comment by CristinaRO** [comment]
> It looks like that error may be unrelated to this upgrade - I'm getting it on `develop` too, and so is George. Would probablu be good to confirm Cristina and George are able to run this fine in their local environments, but otherwise I think it's good to go

I'm getting the same errors in the log. It's "interesting" that the log says `500 Internal Server Error` but doesn't surface it as such in the browser.

**Comment by CristinaRO** [comment]
I think the `Pundit::PolicyScopingNotPerformedError` is related to https://stackoverflow.com/questions/50172367/pundit-authorizationnotperformederror-policyscopingnotperformederror.

We skip the policy scope verification for the activities index https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/app/controllers/activities_controller.rb#L8 because we're using `service_owner` to distinguish between what each type of user should access, and unauthenticated visitors are booted out earlier in the process.

We have the same mechanisms for restricting access to the reports index, so we should probably skip the policy scope verification.

This is not directly related to ruby 3.0, however, so we can tackle it as a separate PR.

**Review by Gweaton — APPROVED** [review]
This looks good to me - probably worth adding this to the CHANGELOG as it's worth capturing this if it's going in its own release?

**Comment by jkempster34** [comment]
> This looks good to me - probably worth adding this to the CHANGELOG as it's worth capturing this if it's going in its own release?

Thanks 🙏 and done

**Comment by jkempster34** [comment]
[Upgrade to Ruby 3](https://trello.com/c/7Bq3osUp/2794-upgrade-to-ruby-3)

**Pull request merged**
