### PR TITLE
2068 user lists all refunds in a report

### PR DESCRIPTION
**Pull request by pezholio**
This builds on the pattern we already have for grouped transactions to display refunds added in a report, grouped by activity. I've made a couple of refactors along the way, including renaming the transactions controller and adding some utility services to fetch grouped transactions to help with testing and keep controllers tidy.

image

### CODE REVIEW

**Comment by pezholio** [comment]
[User lists all refunds in a report](https://trello.com/c/2cEVGLk1/2068-user-lists-all-refunds-in-a-report)

**Review by CristinaRO — COMMENTED** [review]
I'm not ignoring the requests to review this PR, but it's quite big and involved. I'm approx halfway through.

**Review by edavey — APPROVED** [review]
Very clear. I think it works well including the refunds on the "Actuals" tab.

**Comment by pezholio** [comment]
Cool, ta! 👍

**Pull request merged**
