### PR TITLE
Generate public rather than pre-signed url for download link

### PR DESCRIPTION
**Pull request by edavey**
It seems to be impossible to generate a pre-signed GET url
using the GPaaS S3 config, either on a bucket which is
created as "public" or "private".

I've identified two ways of generating a working download
link using Terraform / GPaaS:

### 1. Generate a public url rather than a pre-signed url

This has the disadvantage that the links never expire.
However, I think it's adequate in terms of security as the
url is essentially unguessable e.g.

`https://paas-s3-broker-prod-lon-8cc9c2c5-43f7-44bf-a5c1-11c4256feba8.s3.eu-west-2.amazonaws.com/GCRF_spending_breakdown-20220411170906.csv`

### 2. Create a pre-signed url using separate "service key" creds

By generating a separate set of AWS credentials which are
explicitly set to enable external access:

```
cf create-service-key \
  beis-roda-staging-s3-export-download-bucket \
  beis-roda-staging-s3-export-download-bucket \
  -c '{"allow_external_access": true}'
```

and using these to generate a pre-signed URL (on a private
bucket). e.g.

```
presigner_client = Aws::S3::Client.new(
  region: Export::S3UploaderConfig.region,
  credentials: Aws::Credentials.new(
    S3UploaderConfig.presigner_key_id,
    "S3UploaderConfig.presigner_secret"
  )
)

signer = Aws::S3::Presigner.new(client: presigner_client)

url = signer.presigned_url(
  :get_object,
  bucket: Export::S3UploaderConfig.bucket,
  key: "filename"
)
```

However, these "service key" credentials are not
readily available as environment variables. I've asked GPaaS
support for some help in understanding how we might access
them in Terraform.

### Recommendation

I think that (1): the use of public url is a better
(simpler) solution which is adequate in terms of governance
and security.

This data is not sensitive, contains no personally identifiable information
and will ultimately published publicly via IATI.

The contents of the CSV looks like:

```
RODA identifier,Delivery partner identifier,Activity title,Activity level,Activity status,Delivery partner organisation,Actual spend FQ1 2016-2017,Refund FQ1 2016-2017,Actual net FQ1 2016-2017,Actual spend FQ2 2016-2017,Refund FQ2 2016-2017,Actual net FQ2 2016-2017,Actual spend FQ3 2016-2017,Refund FQ3 2016-2017,Actual net FQ3 2016-2017,Actual spend FQ4 2016-2017,Refund FQ4 2016-2017,Actual net FQ4 2016-2017,Actual spend FQ1 2017-2018,Refund FQ1 2017-2018,Actual net FQ1 2017-2018,Actual spend FQ2 2017-2018,Refund FQ2 2017-2018,Actual net FQ2 2017-2018,Actual spend FQ3 2017-2018,Refund FQ3 2017-2018,Actual net FQ3 2017-2018,Actual spend FQ4 2017-2018,Refund FQ4 2017-2018,Actual net FQ4 2017-2018,Actual spend FQ1 2018-2019,Refund FQ1 2018-2019,Actual net FQ1 2018-2019,Actual spend FQ2 2018-2019,Refund FQ2 2018-2019,Actual net FQ2 2018-2019,Actual spend FQ3 2018-2019,Refund FQ3 2018-2019,Actual net FQ3 2018-2019,Actual spend FQ4 2018-2019,Refund FQ4 2018-2019,Actual net FQ4 2018-2019,Actual spend FQ1 2019-2020,Refund FQ1 2019-2020,Actual net FQ1 2019-2020,Actual spend FQ2 2019-2020,Refund FQ2 2019-2020,Actual net FQ2 2019-2020,Actual spend FQ3 2019-2020,Refund FQ3 2019-2020,Actual net FQ3 2019-2020,Actual spend FQ4 2019-2020,Refund FQ4 2019-2020,Actual net FQ4 2019-2020,Actual spend FQ1 2020-2021,Refund FQ1 2020-2021,Actual net FQ1 2020-2021,Actual spend FQ2 2020-2021,Refund FQ2 2020-2021,Actual net FQ2 2020-2021,Actual spend FQ3 2020-2021,Refund FQ3 2020-2021,Actual net FQ3 2020-2021,Actual spend FQ4 2020-2021,Refund FQ4 2020-2021,Actual net FQ4 2020-2021,Actual spend FQ1 2021-2022,Refund FQ1 2021-2022,Actual net FQ1 2021-2022,Actual spend FQ2 2021-2022,Refund FQ2 2021-2022,Actual net FQ2 2021-2022,Forecast FQ3 2021-2022,Forecast FQ4 2021-2022,Forecast FQ1 2022-2023,Forecast FQ2 2022-2023,Forecast FQ3 2022-2023,Forecast FQ4 2022-2023,Forecast FQ1 2023-2024,Forecast FQ2 2023-2024,Forecast FQ3 2023-2024,Forecast FQ4 2023-2024,Forecast FQ1 2024-2025,Forecast FQ2 2024-2025,Forecast FQ3 2024-2025,Forecast FQ4 2024-2025,Forecast FQ1 2025-2026,Forecast FQ2 2025-2026,Forecast FQ3 2025-2026,Forecast FQ4 2025-2026
GCRF-CICA-R12018-ICA\R1\180100,GCRF_RS_BRA_International Collaboration Awards ICA\R1\180100,For a Climate Resilient Amazon - 'FORAMA',Third-party project (level D),Spend in progress,Royal Society,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,74884.11,0,74884.11,0,0,0,0,0,0,74993.38,0,74993.38,0,0,0,0,0,0,0,0,0,74698.22,0,74698.22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
GCRF-MR_C_HSRI-C1_1314MR/M002306/1,MR/M002306/1,Determinants of medical equipment performance to improve management capacity within health system in Viet Nam,Third-party project (level D),Completed,Medical Research Council,6439.4,0,6439.4,0,0,0,0,0,0,0,0,0,6439.38,0,6439.38,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
GCRF-ES_CIm_ECE-2019ES/T004118/1,ES/T004118/1,Supporting Oral Language Development,Third-party project (level D),Spend in progress,Economic & Social Research Council,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,152387.99,0,152387.99,154030.51,0,154030.51,154030.51,0,154030.51,154030.51,0,154030.51,155278.16,0,155278.16,155278.16,0,155278.16,58059.73,0,58059.73,6300.33,6300.33,154866.67,154866.67,154866.75,0,0,0,0,0,0,0,0,0,0,0,0,0
```

### CODE REVIEW

**Comment by edavey** [comment]
> your rationale makes sense, and the changes look plausible. my only concern is i'd like someone other than me to sign off on this being adequately secure

thanks Suze: I will ask for some more eyes on this.

**Comment by erbridge** [comment]
While the URL is unguessable externally (though you have just posted it online), does it matter that a user downloading one CSV can trivially guess other CSVs?

**Comment by edavey** [comment]
Thanks F: not a real bucket name! And no there's only one person generating / using these CSVs....

**Comment by edavey** [comment]
I've had a response from GPaaS, to the effect that it should be possible to access the key within Terraform as per the "service key" documentation at:

https://registry.terraform.io/providers/cloudfoundry-community/cloudfoundry/latest/docs/resources/service_key

e.g we'd define a "service key" resource such as `beis-roda-staging-s3-external-access` and then use its `credentials` property.

**Comment by erbridge** [comment]
@edavey

> And no there's only one person generating / using these CSVs...

As in there's only one person who's _able_ to? If it's the case that someone with access to one CSV intentionally has access to all CSVs and they aren't sharing direct links with other people, then this is probably fine.

**Comment by shuldt** [comment]
can we get this merged today assuming no further issues? cheers :)

**Review by dragon-dxw — APPROVED** [review]
I'd be in general wary of the "unguessable" nature of the URL -- we could probably add additional actually random gubbins to the filename if we really wanted this to be true.

But here and now this seems like a pretty sensible approach.

**Pull request merged**
