### PR TITLE
(2186) Ensure the region logic is clearly described by the IATI export specs

### PR DESCRIPTION
**Pull request by CristinaRO**
## Changes in this PR
- Rephrase specifications to reflect current reality

## Next steps

- [ ] Is an ADR required? An ADR should be added if this PR introduces a change to the architecture.
- [ ] Is a changelog entry required? An entry should always be made in `CHANGELOG.md`, unless this PR is a small tweak which has no impact outside the development team.
- [ ] Do any environment variables need amending or adding?
- [ ] Have any changes to the XML been checked with the IATI validator? See [XML Validation](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/doc/xml-validation.md)

### CODE REVIEW

**Comment by CristinaRO** [comment]
[Ensure IATI export includes the region logic](https://trello.com/c/z5XUUW4f/2186-ensure-iati-export-includes-the-region-logic)

**Review by pezholio — APPROVED** [review]
LGTM 👍

**Comment by edavey** [comment]
Looks like a nice (if rare) occasion of "it just works" after the changes!

**Pull request merged**
