### PR TITLE
(2293) Change `master` to `main`

### PR DESCRIPTION
**Pull request by CristinaRO**
## Changes in this PR
- Rename `master` branch to `main`

**NB** Releasing these changes, which ensure the workflows will keep working, needs to be coordinated with renaming the branch.

## Screenshots of UI changes

N/A

## Next steps

- [ ] Is an ADR required? An ADR should be added if this PR introduces a change to the architecture.
- [x] Is a changelog entry required? An entry should always be made in `CHANGELOG.md`, unless this PR is a small tweak which has no impact outside the development team.
- [ ] Do any environment variables need amending or adding?
- [ ] Have any changes to the XML been checked with the IATI validator? See [XML Validation](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/doc/xml-validation.md)

### CODE REVIEW

**Comment by CristinaRO** [comment]
[Change 'master' to 'main'](https://trello.com/c/7V0MhSrc/2293-change-master-to-main)

**Review by Gweaton — APPROVED** [review]
This looks good to me - I've checked out locally and searched for `master` but can't find any relevant references to it - think this should be good to go.

**Review by yndajas — APPROVED** [review]

**Comment by yndajas** [comment]
Do these need updating? The other remaining `master` results seemed to relate to other repos

image

**Comment by CristinaRO** [comment]
> Do these need updating? The other remaining `master` results seemed to relate to other repos
> 
> image

I don't think we _can_ change this yet; there is an open issue for it: https://github.com/rails/rails/issues/43601

**Comment by yndajas** [comment]
> > Do these need updating? The other remaining `master` results seemed to relate to other repos
> > image
> 
> I don't think we _can_ change this yet; there is an open issue for it: [rails/rails#43601](https://github.com/rails/rails/issues/43601)

Yep, I'm confusing branches and environment, because you can use environment-specific credentials like `production.key` (not `main.key`)

**Review by yndajas — APPROVED** [review]

**Pull request merged**
