### PR TITLE
(2825) Upgrade sidekiq

### PR DESCRIPTION
**Pull request by CristinaRO**
## Changes in this PR
- Upgrade sidekiq to a non-vulnerable version

## Screenshots of UI changes

N/A

## Next steps

- [ ] Is an ADR required? An ADR should be added if this PR introduces a change to the architecture.
- [ ] Is a changelog entry required? An entry should always be made in `CHANGELOG.md`, unless this PR is a small tweak which has no impact outside the development team.
- [ ] Do any environment variables need amending or adding?
- [ ] Have any changes to the XML been checked with the IATI validator? See [XML Validation](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/doc/xml-validation.md)

### CODE REVIEW

**Comment by mec** [comment]
Did we find out which version of Redis we use in production?

**Comment by CristinaRO** [comment]
> Did we find out which version of Redis we use in production?

No, which is why this is a draft!

**Comment by CristinaRO** [comment]
[Investigate sidekiq gem updates breaking changes](https://trello.com/c/FrMkWUVN/2825-investigate-sidekiq-gem-updates-breaking-changes)

**Review by mec — APPROVED** [review]
🚢

**Pull request merged**
